# Generated by Django 6.0.6 on 2026-07-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_peoplecontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecontact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
