# Generated by Django 6.0.6 on 2026-07-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='operating_days',
            field=models.CharField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shop',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
