# Generated by Django 6.0.6 on 2026-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shop_operating_days_shop_operating_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
